### ISSUE TITLE
 add two node into AnimatedVBox at first and it cause a NullPointerException

### ISSUE THREAD

**Issue by stars-one** [iAmGio/animated#1]
I use the version 0.40

I just add 2 node into the `AnimatedVBox`
```
val contentVbox = AnimatedVBox(AnimationPair(null,BounceOutRight()))
        contentVbox.add(Text("hello"))
        contentVbox.add(Text("hell2o"))
```

the exception is this

```
java.lang.NullPointerException
	at eu.iamgio.animated.AnimatedContainer$Handler.relocate(AnimatedContainer.java:180)
	at eu.iamgio.animated.AnimatedContainer$Handler.lambda$null$0(AnimatedContainer.java:133)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
```

the image is this

![](https://img2022.cnblogs.com/blog/1210268/202202/1210268-20220211160512243-1641573797.png)

> imageUrl: https://img2022.cnblogs.com/blog/1210268/202202/1210268-20220211160512243-1641573797.png

by the way,the version of kotlin what you use is to high for my project :joy: 

I just use the kotlin 1.3.72 because of use the tornadofx framework

**Comment by iAmGio** [comment]
Hi there!
I haven't tested your code, but I can tell you the error comes from the `null` argument you pass to `AnimationPair`, which should be the entrance animation and is required, as the [documentation](https://github.com/iAmGio/animated/blob/master/src/main/java/eu/iamgio/animated/AnimationPair.java#L15) of its constructor says. I could add a specific exception to make it clearer.

> by the way,the version of kotlin what you use is to high for my project

I see, I will lower it down. I had not considered this scenario.

**Comment by iAmGio** [comment]
Hi @stars-one, you might be interested in checking [v0.4.2](https://github.com/iAmGio/animated/releases/tag/v0.4.2) out. Have a good day!

**Comment by iamgio** [comment]
Might be related to this issue: `Animation.none()` was added in b6c65c9fd902db81d2afa5f047c37e8543d9eaa5 as a shortcut for `new Animation(null)` to prevent an animation from playing.
